include depends.mk

SECTION="NetPing modules"
CATEGORY="Base"
TITLE="OWRT-http-agent"

PKG_NAME="OWRT-Http-agent"
PKG_VERSION=0.1
PKG_RELEASE=1


CONF_FILE=http-agent
CONF_DIR=/etc/config/

MODULE_FILES=http-agent.py parser.py
MODULE_FILES_DIR ?= /usr/lib/python3.7/




INSTALL_DIR=

AUTORUN_FILES=owrt_http-agent_autorun

TESTS_SRC_DIR=Tests

all: build preinstall install configure 

ipk: build install

build:
	@echo "Nothing to do"

preinstall:
	@echo "Nothing to do"

configure:
	@echo "Nothing to do"

install:
ifneq ($(INSTALL_DIR),)
	-mkdir -p $(INSTALL_DIR)$(CONF_DIR) 
endif
	cp $(CONF_FILE) $(INSTALL_DIR)/$(CONF_DIR)/
ifneq ($(INSTALL_DIR),)
	mkdir -p $(INSTALL_DIR)$(MODULE_FILES_DIR)
	mkdir -p $(INSTALL_DIR)/etc/init.d
	mkdir -p $(INSTALL_DIR)/etc/rc.d
	for f in $(MODULE_FILES); do cp $${f} $(INSTALL_DIR)$(MODULE_FILES_DIR); done
else
	for f in $(MODULE_FILES); do cp $${f} $(MODULE_FILES_DIR); done
endif


	for f in $(AUTORUN_FILES); do cp $${f} $(INSTALL_DIR)/etc/init.d; done
	mv $(INSTALL_DIR)/etc/init.d/owrt_http-agent_autorun $(INSTALL_DIR)/etc/init.d/owrt_http-agent
	ln -fs ../init.d/owrt_http-agent $(INSTALL_DIR)/etc/rc.d/S90OWRT-Http-agent

clean:
ifeq ($(INSTALL_DIR),)
	rm -f $(CONF_DIR)$(CONF_FILE)
	for f in $(MODULE_FILES); do rm -f $(MODULE_FILES_DIR)/$${f}; done
	rm -f /etc/init.d/owrt_http-agent
	rm -f /etc/rc.d/S90OWRT-Http-agent
else
	rm -rf $(INSTALL_DIR)
endif
