include depends.mk

SECTION="NetPing modules"
CATEGORY="Base"
TITLE="OWRT-http-agent"

PKG_NAME="OWRT-Http-Agent"
PKG_VERSION=0.1
PKG_RELEASE=1
PKG_DEPENDS=OWRT-log

CONF_FILE=http-agent
CONF_DIR=/etc/config/

MODULE_FILES=http-agent.py
MODULE_FILES_DIR ?= /usr/lib/python3.7/

ETC_FILES=etc/configs/http-agent
ETC_FILES_DIR=etc/configs

INSTALL_DIR=

TESTS_SRC_DIR=Tests

all: build preinstall install configure 

ipk: build install

build:
	@echo "Nothing to do"

preinstall:
	@echo "Nothing to do"

configure:
	@echo "Nothing to do"

install:
ifneq ($(INSTALL_DIR),)
	-mkdir -p $(INSTALL_DIR)$(CONF_DIR) 
endif
	cp $(CONF_FILE) $(INSTALL_DIR)/$(CONF_DIR)
ifneq ($(INSTALL_DIR),)
	mkdir -p $(INSTALL_DIR)$(MODULE_FILES_DIR)
	for f in $(MODULE_FILES); do cp $${f} $(INSTALL_DIR)$(MODULE_FILES_DIR); done
else
	for f in $(MODULE_FILES); do cp $${f} $(MODULE_FILES_DIR); done
endif
	mkdir -p $(INSTALL_DIR)$(ETC_FILES_DIR)
	for f in $(ETC_FILES); do cp etc/$${f} $(INSTALL_DIR)$(ETC_FILES_DIR); done
	mkdir -p $(INSTALL_DIR)$(ETC_FILES_DIR)$(ETC_FILES_COMMANDS_DIR)
	for f in $(ETC_FILES_COMMANDS); do cp etc/$${f} $(INSTALL_DIR)$(ETC_FILES_DIR)$(ETC_FILES_COMMANDS_DIR); done
	cp -r $(TESTS_SRC_DIR) $(INSTALL_DIR)$(ETC_FILES_DIR)
	for f in $(AUTORUN_FILES); do cp $${f} $(INSTALL_DIR)/etc/init.d; done
	mv $(INSTALL_DIR)/etc/init.d/owrt_email_autorun $(INSTALL_DIR)/etc/init.d/owrt_email
	ln -fs ../init.d/owrt_email $(INSTALL_DIR)/etc/rc.d/S90OWRT-Email

clean:
ifeq ($(INSTALL_DIR),)
	rm -f $(CONF_DIR)$(CONF_FILE)
	for f in $(MODULE_FILES); do rm -f $(MODULE_FILES_DIR)/$${f}; done
	rm -rf $(ETC_FILES_DIR)
	rm -f /etc/init.d/owrt_email
	rm -f /etc/rc.d/S90OWRT-Email
else
	rm -rf $(INSTALL_DIR)
endif
