#!/bin/sh /etc/rc.common
# Copyright (C) 2023 NetPing

START=90
STOP=90

USE_PROCD=1




start_service() {
        procd_open_instance
        procd_set_param command python3 /usr/lib/python3.7/http-agent.py &> /dev/null
        procd_close_instance
}
